# Generated by Django 6.1.1 on 2026-09-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('admin', 'Admin'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('lab_technician', 'Lab Technician')], max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ug_qualification', models.CharField(blank=True, max_length=255)),
                ('pg_qualification', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(max_length=100)),
                ('appointment_nature', models.CharField(blank=True, choices=[('regular', 'Regular'), ('contractual', 'Contractual'), ('deputation', 'Deputation'), ('part_time', 'Part Time'), ('adhoc', 'Adhoc')], max_length=30)),
                ('registration_number', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('experience', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
